<?php
session_start();
require_once '../config/config.php';
require_once '../lib/dompdf/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../validate/login.php");
    exit();
}

$users = $conn->query("SELECT id, full_name FROM users WHERE (role != 'admin' OR role IS NULL OR role = '')");

$editMode = isset($_GET['id']);
$enrollment = [
    'user_id' => '',
    'course_id' => '',
    'status' => 'Active',
    'progress' => 0,
    'enrolled_at' => date('Y-m-d\TH:i'),
    'completed_at' => ''
];
$errors = [];
$invoice_path = '';

// Restore invoice after redirect
if (isset($_SESSION['invoice_path'])) {
    $invoice_path = $_SESSION['invoice_path'];
    unset($_SESSION['invoice_path']);
}

if ($editMode) {
    $id = intval($_GET['id']);
    $stmt = $conn->prepare("SELECT * FROM enrollments WHERE id = ? AND is_deleted = 0");
    $stmt->bind_param("i", $id);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($result->num_rows < 1) {
        die("Enrollment not found.");
    }
    $enrollment = $result->fetch_assoc();
}

$users = $conn->query("SELECT id, full_name FROM users WHERE role IN ('student', 'instructor') OR role IS NULL OR role = ''");
$courses = $conn->query("SELECT id, title, price FROM courses WHERE status = 'Published'");

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $user_id = intval($_POST['user_id']);
    $course_id = intval($_POST['course_id']);
    $status = $_POST['status'];
    $progress = intval($_POST['progress']);
    $enrolled_at = $_POST['enrolled_at'];
    $completed_at = $_POST['completed_at'];
    $price = "0.00";

    if ($user_id < 1 || $course_id < 1 || $progress < 0 || $progress > 100 || !in_array($status, ['Active', 'Completed', 'Dropped', 'Pending'])) {
        $errors[] = "Invalid input. Please verify fields.";
    }

    if (!$enrolled_at) $enrolled_at = date('Y-m-d H:i:s');

    // Check duplicate only on new insert
    if (!$editMode) {
        $checkDup = $conn->prepare("SELECT id FROM enrollments WHERE user_id = ? AND course_id = ? AND is_deleted = 0");
        $checkDup->bind_param("ii", $user_id, $course_id);
        $checkDup->execute();
        if ($checkDup->get_result()->num_rows > 0) {
            $errors[] = "❌ This user is already enrolled in the selected course.";
        }
        $checkDup->close();
    }

    if (empty($errors)) {
        if ($editMode) {
            $stmt = $conn->prepare("UPDATE enrollments SET user_id=?, course_id=?, status=?, progress=?, enrolled_at=?, completed_at=? WHERE id=?");
            $stmt->bind_param("iissssi", $user_id, $course_id, $status, $progress, $enrolled_at, $completed_at, $id);
        } else {
            $enrollment_id = sprintf("ENR%s%s%s%s", date("Y"), $course_id, $user_id, rand(1000, 9999));
            $stmt = $conn->prepare("INSERT INTO enrollments (user_id, course_id, enrollment_id, status, progress, enrolled_at, completed_at) VALUES (?, ?, ?, ?, ?, ?, ?)");
            $stmt->bind_param("iississ", $user_id, $course_id, $enrollment_id, $status, $progress, $enrolled_at, $completed_at);

            $pay_stmt = $conn->prepare("INSERT INTO payments (user_id, course_id, enrollment_id, amount, status, transaction_date) VALUES (?, ?, ?, ?, ?, NOW())");
            $pay_status = 'success';
            $pay_stmt->bind_param("iisss", $user_id, $course_id, $enrollment_id, $price, $pay_status);
        }

        if ($stmt->execute()) {
            if (!$editMode) {
                $pay_stmt->execute();
                $courseRes = $conn->query("SELECT title FROM courses WHERE id = $course_id");
                $course = $courseRes->fetch_assoc();
                $invoice_path = generateInvoice($course['title'], $user_id, $enrollment_id, $price, $status);
                $_SESSION['invoice_path'] = $invoice_path;
            }

            $_SESSION['success'] = $editMode ? "✅ Enrollment updated." : "✅ User enrolled successfully.";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit();
        } else {
            $errors[] = "Database error: " . $stmt->error;
        }
    }
}

function generateInvoice($course_title, $user_id, $enrollment_id, $amount, $status) {
    $amount = number_format($amount, 2);
    $date = date("Y-m-d H:i");
    $html = <<<HTML
<style>
    body { font-family: DejaVu Sans; font-size: 14px; }
    h2 { color: #4CAF50; text-align: center; }
    .row { margin-bottom: 6px; }
</style>
<h2>Enrollment Invoice</h2>
<div class="row"><strong>Enrollment ID:</strong> $enrollment_id</div>
<div class="row"><strong>User ID:</strong> $user_id</div>
<div class="row"><strong>Course:</strong> $course_title</div>
<div class="row"><strong>Status:</strong> $status</div>
<div class="row"><strong>Amount:</strong> \$$amount</div>
<div class="row"><strong>Date:</strong> $date</div>
<hr>
<p style="font-size:12px;">This invoice was auto-generated by admin enrollment panel.</p>
HTML;

    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $file = "../courses/invoices/invoice-{$enrollment_id}.pdf";
    file_put_contents($file, $dompdf->output());

    return $file;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $editMode ? "Edit" : "Manual Enroll" ?> Enrollment</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f8f9fa;
            overflow-x: hidden;
        }
        .admin-page-wrapper {
            margin-left: 250px;
            padding: 30px;
            min-height: 100vh;
            background-color: #f8f9fa;
        }
        @media (max-width: 768px) {
            .admin-page-wrapper {
                margin-left: 0;
                padding: 20px 15px;
            }
        }
    </style>
</head>
<body>

<?php include '../includes/header.php'; ?>
<?php include '../includes/admin-sidebar.php'; ?>

<div class="admin-page-wrapper">
<div class="container mt-5">
    <h2><i class="fas fa-edit me-2"></i><?= $editMode ? "Edit Enrollment" : "Manually Enroll Students" ?></h2>
    <a href="manage-enrollments.php" class="btn btn-secondary mb-4"><i class="fas fa-arrow-left"></i> Back to Enrollments</a>

    <form method="POST" id="enrollmentForm">
        <div class="mb-3">
            <label for="user_id" class="form-label">Student</label>
            <select name="user_id" id="user_id" class="form-select" <?= $editMode ? 'disabled' : '' ?> required>
                <option value="">Select User</option>
                <?php while($user = $users->fetch_assoc()): ?>
                    <option value="<?= $user['id'] ?>" <?= ($editMode && $user['id'] == $enrollment['user_id']) ? 'selected' : '' ?>>
                        <?= htmlspecialchars($user['full_name']) ?>
                    </option>
                <?php endwhile; ?>
            </select>
            <?php if ($editMode): ?>
                <input type="hidden" name="user_id" value="<?= $enrollment['user_id'] ?>">
            <?php endif; ?>
        </div>

        <div class="mb-3">
            <label for="course_id" class="form-label">Course</label>
            <select name="course_id" id="course_id" class="form-select" required>
                <option value="">Select Course</option>
                <?php while ($c = $courses->fetch_assoc()): ?>
                    <option value="<?= $c['id'] ?>" <?= $enrollment['course_id'] == $c['id'] ? 'selected' : '' ?>>
                        <?= htmlspecialchars($c['title']) ?>
                    </option>
                <?php endwhile; ?>
            </select>
        </div>

        <div class="mb-3">
            <label class="form-label">Status</label>
            <select name="status" class="form-select" required>
                <?php foreach (['Active', 'Completed', 'Dropped', 'Pending'] as $opt): ?>
                    <option value="<?= $opt ?>" <?= $enrollment['status'] === $opt ? 'selected' : '' ?>><?= $opt ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="mb-3">
            <label for="progress" class="form-label">Progress %</label>
            <input type="number" class="form-control" name="progress" min="0" max="100" value="<?= $enrollment['progress'] ?>" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Enrollment Date</label>
            <input type="datetime-local" class="form-control" name="enrolled_at" value="<?= date('Y-m-d\TH:i', strtotime($enrollment['enrolled_at'])) ?>" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Completion Date (optional)</label>
            <input type="datetime-local" class="form-control" name="completed_at" value="<?= $enrollment['completed_at'] ? date('Y-m-d\TH:i', strtotime($enrollment['completed_at'])) : '' ?>">
        </div>

        <button type="submit" class="btn btn-success"><i class="fas fa-check-circle me-1"></i><?= $editMode ? "Update Enrollment" : "Enroll Student" ?></button>
    </form>
</div>
</div>

<?php if ($invoice_path && file_exists($invoice_path)): ?>
<script>
document.addEventListener("DOMContentLoaded", () => {
    const link = document.createElement("a");
    link.href = "<?= $invoice_path ?>";
    link.download = "<?= basename($invoice_path) ?>";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
});
</script>
<?php endif; ?>

<script>
document.addEventListener("DOMContentLoaded", () => {
    <?php if (isset($_SESSION['success'])): ?>
    Swal.fire({
        icon: 'success',
        title: <?= json_encode($_SESSION['success']) ?>,
        toast: true,
        position: 'top-end',
        timer: 4000,
        timerProgressBar: true,
        showConfirmButton: false
    });
    <?php unset($_SESSION['success']); endif; ?>

    <?php if (!empty($errors)): ?>
    Swal.fire({
        icon: 'error',
        title: 'Validation Error',
        html: <?= json_encode(implode("<br>", array_map("htmlspecialchars", $errors))) ?>,
        confirmButtonColor: '#d33'
    });
    <?php endif; ?>

    const form = document.getElementById('enrollmentForm');
    if (form) {
        form.addEventListener("submit", function(e) {
            e.preventDefault();
            Swal.fire({
                title: 'Confirm Submission',
                text: "Are you sure you want to proceed?",
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Yes, Submit',
                cancelButtonText: 'Cancel',
                confirmButtonColor: '#28a745',
                cancelButtonColor: '#d33'
            }).then((result) => {
                if (result.isConfirmed) {
                    form.submit();
                }
            });
        });
    }
});
</script>

</body>
</html>