<?php
session_start();
require_once '../config/config.php';
require_once '../lib/dompdf/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'instructor') {
    header("Location: ../validate/login.php");
    exit;
}

$instructor_id = $_SESSION['user_id'];
$errors = [];
$invoice_path = '';
$success = '';

// Instructor's Courses
$course_stmt = $conn->prepare("SELECT id, title, price FROM courses WHERE instructor_id = ? AND status = 'Published'");
$course_stmt->bind_param("i", $instructor_id);
$course_stmt->execute();
$courses = $course_stmt->get_result();

// Students
$students = $conn->query("SELECT id, full_name FROM users WHERE role IS NULL OR role = '' OR role = 'student'");

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $user_id = intval($_POST['user_id']);
    $course_id = intval($_POST['course_id']);
    $enrolled_at = $_POST['enrolled_at'] ?: date("Y-m-d H:i:s");

    if (!$user_id || !$course_id) $errors[] = "Student and course are required.";

    $verify_stmt = $conn->prepare("SELECT title, price FROM courses WHERE id = ? AND instructor_id = ? AND status = 'Published'");
    $verify_stmt->bind_param("ii", $course_id, $instructor_id);
    $verify_stmt->execute();
    $course = $verify_stmt->get_result()->fetch_assoc();
    if (!$course) $errors[] = "Course not found or not owned by you.";

    $dupe_check = $conn->prepare("SELECT 1 FROM enrollments WHERE user_id = ? AND course_id = ? AND is_deleted = 0");
    $dupe_check->bind_param("ii", $user_id, $course_id);
    $dupe_check->execute();
    $dupe_check->store_result();
    if ($dupe_check->num_rows > 0) $errors[] = "Student already enrolled in this course.";

    if (empty($errors)) {
        $price = 0.00;
        $status = 'pending';
        $enrollment_id = sprintf("ENR%s%s%s%s", date("Y"), $course_id, $user_id, rand(1000, 9999));

        $enroll_stmt = $conn->prepare("INSERT INTO enrollments (user_id, course_id, enrollment_id, status, progress, enrolled_at) VALUES (?, ?, ?, ?, 0, ?)");
        $enroll_stmt->bind_param("iisss", $user_id, $course_id, $enrollment_id, $status, $enrolled_at);
        $enroll_stmt->execute();

        $pay_stmt = $conn->prepare("INSERT INTO payments (user_id, course_id, enrollment_id, amount, status, transaction_date) VALUES (?, ?, ?, ?, ?, NOW())");
        $pay_stmt->bind_param("iisss", $user_id, $course_id, $enrollment_id, $price, $status);
        $pay_stmt->execute();

        $invoice_path = generateInvoice($course['title'], $user_id, $enrollment_id, $price, ucfirst($status));
        $_SESSION['success'] = "✅ Enrollment created. Invoice will download.";
        header("Location: add-enrollments.php?invoice=" . basename($invoice_path));
        exit();
    }
}

function generateInvoice($course_title, $user_id, $enrollment_id, $amount, $status) {
    $amount = number_format($amount, 2);
    $date = date("Y-m-d H:i");
    $html = <<<HTML
<style>
    body { font-family: DejaVu Sans; font-size: 14px; }
    h2 { color: #4CAF50; text-align: center; }
    .row { margin-bottom: 6px; }
</style>
<h2>Enrollment Invoice</h2>
<div class="row"><strong>Enrollment ID:</strong> $enrollment_id</div>
<div class="row"><strong>User ID:</strong> $user_id</div>
<div class="row"><strong>Course:</strong> $course_title</div>
<div class="row"><strong>Status:</strong> $status</div>
<div class="row"><strong>Amount:</strong> \$$amount</div>
<div class="row"><strong>Date:</strong> $date</div>
<hr>
<p style="font-size:12px;">Generated by Instructor Manual Enroll Panel.</p>
HTML;

    $options = new Options();
    $options->set('isRemoteEnabled', true);
    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $file = "../courses/invoices/invoice-{$enrollment_id}.pdf";
    file_put_contents($file, $dompdf->output());

    return $file;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manual Enrollments - Instructor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .admin-container {
            margin-left: 250px;
            padding: 20px;
            display: flex;
            flex-direction: row;
            margin-top: 20px;
        }
        @media screen and (max-width: 768px) {
            .admin-container {
                margin-left: 0;
                flex-direction: column;
            }
            
        }
    </style>
</head>
<body>

<?php include '../includes/header.php'; ?>
<?php include_once '../includes/instructor-sidebar.php'; ?>

<div class="admin-container">
<div class="container mt-5">
    <h2><i class="fas fa-user-plus"></i> Manually Enroll a Student</h2>
    <a href="enrollments.php" class="btn btn-secondary mb-4"><i class="fas fa-arrow-left"></i> Back to Enrollments</a>

    <form method="POST">
        <div class="mb-3">
            <label for="user_id" class="form-label">Student</label>
            <select name="user_id" id="user_id" class="form-select" required>
                <option value="">Select Student</option>
                <?php while ($stu = $students->fetch_assoc()): ?>
                    <option value="<?= $stu['id'] ?>"><?= htmlspecialchars($stu['full_name']) ?></option>
                <?php endwhile; ?>
            </select>
        </div>

        <div class="mb-3">
            <label for="course_id" class="form-label">Course</label>
            <select name="course_id" id="course_id" class="form-select" required>
                <option value="">Select Course</option>
                <?php while ($c = $courses->fetch_assoc()): ?>
                    <option value="<?= $c['id'] ?>"><?= htmlspecialchars($c['title']) ?> (<?= number_format($c['price'], 2) ?> USD)</option>
                <?php endwhile; ?>
            </select>
            <small class="text-danger d-block mt-1">⚠️ Free enrollment. You won't earn from this enrollment.</small>
        </div>

        <div class="mb-3">
            <label for="enrolled_at" class="form-label">Enrollment Date</label>
            <input type="datetime-local" name="enrolled_at" id="enrolled_at" class="form-control" value="<?= date('Y-m-d\TH:i') ?>" required>
        </div>

        <div class="mb-3">
            <label class="form-label">Status:</label> <strong>Pending</strong><br>
            <small class="text-danger">⚠️ Enrollment is pending until approved by admin.</small>
        </div>

        <button type="submit" class="btn btn-success"><i class="fas fa-check-circle"></i> Enroll Now</button>
    </form>
</div>
</div>
<!-- SweetAlert2 for errors -->
<?php if (!empty($errors)): ?>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        Swal.fire({
            icon: 'error',
            title: 'Enrollment Error',
            html: `<?= implode('<br>', array_map('htmlspecialchars', $errors)) ?>`
        });
    });
</script>
<?php endif; ?>

<!-- SweetAlert2 for success -->
<?php if (!empty($_SESSION['success'])): ?>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        Swal.fire({
            toast: true,
            position: 'top-end',
            icon: 'success',
            title: <?= json_encode(strip_tags($_SESSION['success'])) ?>,
            showConfirmButton: false,
            timer: 4000,
            timerProgressBar: true
        });
    });
</script>
<?php unset($_SESSION['success']); ?>
<?php endif; ?>

<!-- Auto download if redirected -->
<?php if (isset($_GET['invoice']) && file_exists("../courses/invoices/" . $_GET['invoice'])): ?>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const link = document.createElement("a");
        link.href = "../courses/invoices/<?= $_GET['invoice'] ?>";
        link.download = "<?= $_GET['invoice'] ?>";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    });
</script>
<?php endif; ?>

</body>
</html>